# Generated by Django 4.2 on 2023-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
