# Generated by Django 4.2 on 2023-04-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_alter_users_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
