# Generated by Django 4.2 on 2023-04-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0004_rename_user_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='MyAPI_user',
        ),
    ]
