# Generated by Django 4.2 on 2023-04-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0008_delete_customuser_rename_role_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='MyAPI',
        ),
    ]
