# Generated by Django 4.2 on 2023-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0016_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
