# Generated by Django 4.2 on 2023-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0017_alter_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='France',
            field=models.CharField(default='salah', max_length=20),
            preserve_default=False,
        ),
    ]
