# Generated by Django 4.2 on 2023-04-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0018_myuser_france'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='France',
        ),
    ]
