# Generated by Django 4.2 on 2023-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0020_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='UserID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
