# Generated by Django 4.2 on 2023-05-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0021_alter_product_userid_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAPI.myuser'),
        ),
    ]
