# Generated by Django 4.2 on 2023-06-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0022_alter_product_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Make',
        ),
        migrations.AddField(
            model_name='product',
            name='Model',
            field=models.CharField(default='audi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ModelTrims',
            field=models.CharField(default='audisss', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Year',
            field=models.IntegerField(default=1999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
