# Generated by Django 5.0.6 on 2024-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0024_rename_modeltrims_product_trim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Adresse',
            new_name='pseudo',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
