# Generated by Django 5.0.6 on 2024-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0026_video_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
