# Generated by Django 5.0.6 on 2024-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0027_alter_video_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
