FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ffmpeg && apt-get clean
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5001
CMD ["python", "app.py"]
